### PR TITLE
feat(ofType): expose ofType as lettable operator

### PR DESCRIPTION
**Pull request by jgoz**
Supports using `ofType` directly in lettable operator pipelines.

Closes #186

- [x] I have read the [Contributor Guide](https://github.com/redux-observable/redux-observable/blob/master/CONTRIBUTING.md)
- [x] My commit messages are in [conventional-changelog-standard](https://github.com/redux-observable/redux-observable/blob/master/CONTRIBUTING.md#sending-a-pull-request) format.

### CODE REVIEW

**Comment by jgoz** [comment]
Happy to contribute! Thanks for the quick turnaround 😃

**Comment by rgbkrk** [comment]
Thank you so much!

**Comment by BerkeleyTrue** [comment]
@jayphelps when will this be released?

**Comment by jayphelps** [comment]
@BerkeleyTrue there ended up being an issue with it with versions of rxjs pre-lettable. I'm still debugging.

**Comment by jayphelps** [comment]
I think the issue is actually not version, but that the global version of rxjs doesn't provide let as `letProto`, it provides it as `letBind`. I dunno, shit is confusing.

**Comment by jayphelps** [comment]
That is indeed the issue. The named export is called `letProto` but the prototype name is `letBind`, so webpack-rxjs-externals doesn't correctly resolve it for UMD. Tracking here: https://github.com/ReactiveX/rxjs/issues/3024

Not sure of how to work around..even if a new rxjs version fixes this, we wouldn't be able to support older versions of rxjs which is a deal breaker IMO. Anyone have ideas?

**Comment by jgoz** [comment]
@jayphelps Hmm, I wasn't aware of `webpack-rxjs-externals`. We can't go back in time and rename `letProto` to `letBind`, so maybe the simplest solution is to copy the implementation back into `ActionsObservable.ofType` instead of using the operator directly.

Other options:
- Inside `ActionsObservable.js` do `import 'rxjs/add/operator/let'` and use `let`/`letBind` directly (downside being it pollutes `Observable` for users, but `let` is super tiny...)
- Expose `ofType` as a bindable operator too (`ofTypeProto`? using the lettable version internally) and binding to that in `ActionsObservable`

**Comment by jayphelps** [comment]
lol what I am thinking...let is so simple we don't even need to use it. 😄 

```js
return ofType(...keys)(this)
```

I'll make this change.

**Comment by jgoz** [comment]
Haha, that is by far the best option and I wish I'd thought of it initially 😉

**Comment by jayphelps** [comment]
#345 fixes that issue. I also want to get #346 reviewed and merged before we release the next version. Reviews from anyone are welcome!

**Comment by jayphelps** [comment]
Released in v0.17.0 🎈

**Pull request merged**
