### PR TITLE
feat(dependencies): Loosen peerDependencies

### LINKED ISSUE #358: Feature: Loosen peerDependencies
**Do you want to request a *feature* or report a *bug*?**  
Feature request

We're currently working with `redux-observable`, and due to the way `peerDependencies` are described, installing logs warnings in the terminal.

I'd like to propose a fix to this by loosening peer dependency versions.

PR #359

### PR DESCRIPTION
**Pull request by mrmckeb**
A PR to loosen the `peerDependencies` in `redux-observable`. See #358 for further details.

Closes #358.

- [x] I have read the [Contributor Guide](https://github.com/redux-observable/redux-observable/blob/master/CONTRIBUTING.md)
- [x] My commit messages are in [conventional-changelog-standard](https://github.com/redux-observable/redux-observable/blob/master/CONTRIBUTING.md#sending-a-pull-request) format.

### CODE REVIEW

**Comment by jayphelps** [comment]
thanks for the PR!  can you clarify under what circumstances this allows that weren't before? #358 doesn't clarify. I'm guessing prerelease/beta versions of rxjs right?

**Comment by mrmckeb** [comment]
Hi @jayphelps, thanks for getting back to me.

When using `redux-observable` (`0.17.0`), we're receiving warnings in Yarn about unmet peer dependencies.
```
warning redux-observable@0.17.0" has unmet peer dependency "redux@3.*".
warning redux-observable@0.17.0" has unmet peer dependency "rxjs@^5.0.0".
```

This project's `package.json` has:
```
...
"redux": "^3.7.2",
"rxjs": "^5.5.2",
"redux-observable": "^0.17.0",
...
```

I understand that the current implementation is as per the npm [semver docs](https://docs.npmjs.com/misc/semver), but for whatever reason this does not seem to be working with Yarn.

This PR aims to resolve that by defining a range that is more expressive using `primitive` range syntax, and as also less strict around beta versions.

**Comment by jayphelps** [comment]
@mrmckeb thanks for the explanation, that makes sense. But you're right about it not previously allowing beta/alpha/etc so I'm thankful for this PR! Thank you!

**Comment by mrmckeb** [comment]
Thanks @jayphelps, and great work on this library.

**Pull request merged**
