### PR TITLE
Dynamically add epics after store creation

### PR DESCRIPTION
**Pull request by alisd23**
For issue #52

### CODE REVIEW

**Comment by jayphelps** [comment]
We'll have to sit on this for a bit cause I imagine we want to instead follow redux's pattern of having a `replaceDelegator(rootDelegator)` analogous to `replaceReducer(rootReducer)`. Then if we have that is some ways it makes this redundant--though I'm not writing it off completely cause it does in fact reduce boilerplate even with `replaceDelegator`.

**Comment by alisd23** [comment]
No problem, I'm interested to see a **replaceDelegator** solution

**Comment by jeffbski** [comment]
`replaceDelegator` would be nice, but if that is too difficult to solve due to accumulated state then `addDelegator` would solve the need for lazy loading and I believe would be significantly easier to implement. So we could consider that as a solution which meets 90% of common needs.

**Comment by jeffbski** [comment]
And I didn't realize that this PR actually had implemented addDelegator already. So it is already done and quite simple. If replaceDelegator is on the long term plan, then I'd vote for getting this in for now and it can be removed if and when replaceDelegator is ready in the future.

**Comment by jayphelps** [comment]
Our current thinking is instead of providing the ability to add them (cause then we'd need a way to remove them) we'll just provide a way to replace it. Works for both this case and the hot reloading case too and is more inline with redux's `replaceReducer`.

Check out https://github.com/redux-observable/redux-observable/pull/75

**Comment by jayphelps** [comment]
Here's simple Rx for anyone who wants to add new Epics without tearing down the old ones:

http://jsbin.com/tuxikuk/edit?js,output

```js
const epic$ = new BehaviorSubject(combineEpics(epic1, epic2));
const rootEpic = (action$, store) =>
  epic$.mergeMap(epic =>
    epic(action$, store)
  );

// sometime later...add another Epic, keeping the state of the old ones...
epic$.next(asyncEpic1);
// and again later add another...
epic$.next(asyncEpic2);
```

**Comment by jayphelps** [comment]
Hey @alisd23, super appreciate your work on this. We did decide to keep the middleware only supporting a single, root epic for now. Hope you understand 👯 

As with most things, we'll continue to evaluate this so it may one day make sense to add this functionality. For now, people can fairly trivially brew their own method, like:

```js
const epic$ = new BehaviorSubject(combineEpics(epic1, epic2));
const rootEpic = (action$, store) =>
  epic$.mergeMap(epic =>
    epic(action$, store)
  );

// sometime later...add another Epic, keeping the state of the old ones...
epic$.next(asyncEpic1);
// and again later add another...
epic$.next(asyncEpic2);
```

Thanks again!

**Comment by alisd23** [comment]
@jayphelps Sorry totally forgot about this...
No problem :+1:

**Comment by asvishnyakov** [comment]
https://github.com/redux-observable/redux-observable/issues/525#issuecomment-397431316

**Pull request closed without merging**
