### PR TITLE
remove extra 'and'

### PR DESCRIPTION
**Pull request by NikaBuligini**
- [x] I have read the [Contributor Guide](https://github.com/redux-observable/redux-observable/blob/master/CONTRIBUTING.md)
- [x] My commit messages are in [conventional-changelog-standard](https://github.com/redux-observable/redux-observable/blob/master/CONTRIBUTING.md#sending-a-pull-request) format.

Hello,

I just remove extra word. Nothing special.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Thanks!

**Comment by rgbkrk** [comment]
When I merged your PR I switched it over to the conventional changelog format by prepending `docs:`

**Comment by NikaBuligini** [comment]
It looks better

**Comment by NikaBuligini** [comment]
It looks better

**Pull request merged**
