### PR TITLE
doc(Error Handling): Fix indentation

### PR DESCRIPTION
**Pull request by brettdh**
I noticed that the indentation was wonky (mix of tabs and spaces, not aligned), so I
fixed that to be two spaces at every level.

*Update: removed imports per discussion below*

- [x] I have read the [Contributor Guide](https://github.com/redux-observable/redux-observable/blob/master/CONTRIBUTING.md)
- [x] My commit messages are in [conventional-changelog-standard](https://github.com/redux-observable/redux-observable/blob/master/CONTRIBUTING.md#sending-a-pull-request) format.

### CODE REVIEW

**Comment by jayphelps** [comment]
Hey thanks for the PR! All the examples intentionally do not have imports for operators because there are several ways to do it and redux-observable does not want to take a stance on the “best” way. It’s mentioned in Epics.md

> IMPORTANT: redux-observable does not add any of the RxJS operators to the Observable.prototype so you will need to import the ones you use or import all of them in your entry file.
> 
> Because there are many ways to add them, our examples will not include any imports. If you want to add every operator, put import 'rxjs'; in your entry index.js. Learn more.

**Comment by brettdh** [comment]
Ha, serves me right for jumping to the example without carefully reading the context. :) I saw the bit about needing to explicitly import operators, but missed the bit about the examples.

**Comment by jayphelps** [comment]
Thanks again! 😄

**Comment by jayphelps** [comment]
whoops, didn't see you changed just to fix the indentation. Reopening and merging. Thanks!

**Pull request merged**
