### PR TITLE
Add EPIC_END type

### PR DESCRIPTION
**Pull request by Ailrun**
- [x] I have read the [Contributor Guide](https://github.com/redux-observable/redux-observable/blob/master/CONTRIBUTING.md)
- [x] My commit messages are in [conventional-changelog-standard](https://github.com/redux-observable/redux-observable/blob/master/CONTRIBUTING.md#sending-a-pull-request) format.

### CODE REVIEW

**Comment by Ailrun** [comment]
@jayphelps Is there any problem with this PR? why don't anyone add comments on this PR?

**Comment by jayphelps** [comment]
@Ailrun Nope! it was just missed because I was out during that team for surgery. Sorry for the delay.

**Comment by jayphelps** [comment]
This finally landed in 0.17.0

**Comment by Ailrun** [comment]
@jayphelps oh, thank you for notifiying!

**Pull request merged**
