### PR TITLE
Validate epic returns Subscribable

### PR DESCRIPTION
**Pull request by kwonoj**
- [x] I have read the [Contributor Guide](https://github.com/redux-observable/redux-observable/blob/master/CONTRIBUTING.md)
- [x] My commit messages are in [conventional-changelog-standard](https://github.com/redux-observable/redux-observable/blob/master/CONTRIBUTING.md#sending-a-pull-request) format.

related to #64.

This PR updates `combineEpic` to have naïve check to given epic is `Subscribable`, by checking if it has `symbol` or either simply has `subscribe` to allow subscribe to it. Latter is for use cases of user using adapter and using non-Rx based which doesn't have symbol yet.

In addition to those, simplified test scripts does not require separate build for test specs by allowing mocha directly compiles it.

### CODE REVIEW

**Comment by jayphelps** [comment]
Sorry for the delay, was on vacation. I don't believe we need to test for symbol.observable because they would only be using this `combineEpics` if they are using RxJS v5. If they are using anything else with an adapter, they would need to use their own equivalent. Which reminds me that the adapters I maintain should probably include their own `combineEpics` since the default one won't work with anything but rxjs v5.

**Comment by kwonoj** [comment]
I see. feel freely close PR if isn't feasible.

**Comment by jayphelps** [comment]
@kwonoj if we do want to enforce it be an observable, I don't mind the subscribe check! the existing is an even more naive check because I'm somewhat reluctant to not support the same signature as `Observable.from`. I don't really have a use case for peoples epics returning an array/promise/etc but I could see someone being overly clever with a generator...not that I would recommend that. I dunno. it's almost certainly ok. I just need to stew on it a bit.

**Comment by kwonoj** [comment]
I think in general someone experienced with `redux-observable` probably fine without this PR, as they certainly know epic should return observable. It's just helping initial dive in, including myself there was really simple errors to forget return observable and spend several hours to figure out why code is not working. So, it may helpful for someone but not obviously benefitable for everyone, reason I'm ok if you don't see feasibility feel free to close.

**Comment by jayphelps** [comment]
@kwonoj I'm very interested in this. What were you returning that passed a truthy check but wasn't an observable?

**Comment by jayphelps** [comment]
@kwonoj I _really_ want these sorts of check for newcomers, not for the people already familiar. So your insight will help guide.

**Comment by kwonoj** [comment]
@jayphelps apologize I don't even recall what was I experienced exactly since I experienced last year(!) and did not leave any memory for it. :/

**Comment by Anujan** [comment]
@jayphelps  For newcomers, a common error may be something like this?

`catch(error => ({ action: 'ACTION_FAILED' }))`

**Comment by jayphelps** [comment]
Closing for now, I think if we were going to do a more robust check it would need to be all the things that Rx supports, Observable/Promise/Iterable/etc

**Comment by kwonoj** [comment]
Yup, got it.

**Pull request closed without merging**
