### PR TITLE
docs(all): wip: update docs for version 1.0.0

### PR DESCRIPTION
**Pull request by evertbouw**
TODO:
- [ ] Troubleshooting
- [ ] Hot module replacement
- [ ] JSBin examples

### CODE REVIEW

**Comment by jayphelps** [comment]
Wonderful start 👏 Thank you sir.

**Comment by oisu** [comment]
Hi, I tried fixing JSBin examples.

2.1. Epics

A Basic Example
https://jsbin.com/pajuteg/edit?html,js,console,output

A Real World Example
https://jsbin.com/zeyoqalufa/edit?html,js,console,output

Accessing the Store's State
https://jsbin.com/xoyujuc/edit?html,js,console,output

4.1. Cancellation
https://jsbin.com/mowosob/edit?html,js,console,output

4.2. Error Handling
https://jsbin.com/wuvasex/edit?html,js,console,output

**Comment by evertbouw** [comment]
Awesome!

**Comment by jayphelps** [comment]
Thanks again folks! I'll PR the rest.

**Pull request merged**
